---
- name: Set up common settings
  ansible.builtin.import_tasks: setup.yml
  tags:
    - setup
    - setup_common

- name: Test common settings
  ansible.builtin.import_tasks: test.yml
  tags:
    - test
    - test_common
