---
- name: Setup OS packages
  ansible.builtin.import_tasks: setup/os_packages.yml
  tags: setup_common_os_packages

- name: Setup the hostname
  ansible.builtin.import_tasks: setup/hostname.yml
  tags: setup_common_hostname

- name: Setup the chronyd
  ansible.builtin.import_tasks: setup/chronyd.yml
  tags: setup_common_chronyd

- name: Setup the firewalld
  ansible.builtin.import_tasks: setup/firewalld.yml
  tags: setup_common_firewalld
