---
- name: Add iptable modules
  community.general.modprobe:
    name: "{{ module }}"
    persistent: present
    state: present
  loop_control:
    loop_var: module
  loop: "{{ rancher_iptables_modules }}"
