---
- name: Set up docker settings
  ansible.builtin.import_tasks: setup.yml
  tags:
    - setup
    - setup_docker

- name: Test docker settings
  ansible.builtin.import_tasks: test.yml
  tags:
    - test
    - test_docker
